[package]
name = "midas-chart"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
midas-core       = { path = "../midas-core" }
midas-data       = { path = "../midas-data" }
midas-indicators = { path = "../midas-indicators" }

bytemuck  = { workspace = true }
chrono    = { workspace = true }
glam      = { workspace = true }
serde     = { workspace = true }
thiserror = { workspace = true }
tracing   = { workspace = true }

[dev-dependencies]
criterion   = { workspace = true }
serde_json  = { workspace = true }

[[bench]]
name = "chart_bench"
harness = false
